<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDhhnwxg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDhhnwxg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDhhnwxg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDhhnwxg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDhhnwxg\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Dhhnwxg',
    'container.build_id' => '6ce9b212',
    'container.build_time' => 1516051073,
));
